### ISSUE TITLE
The branch name is not found if the head is detached

### ISSUE THREAD

**Issue by wcandillon** [PhilWaldmann/grunt-branch-run#1]
This is a problem because within a travis deployment, this grunt command will found HEAD as being the branch name.

PS: great contribution btw!

**Comment by PhilWaldmann** [comment]
yes, that's right! Thx for the hint.
I'll change the script to take the value of `TRAVIS_BRANCH` if it exists. 

Thanks,
Philipp

**Comment by wcandillon** [comment]
that would be awesome :))))
